/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#653e00",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#c0c1ff",
        "primary-container": "#8083ff",
        "on-background": "#e5e1e4",
        "on-secondary-fixed": "#002113",
        "on-primary": "#1000a9",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#005236",
        "on-surface": "#e5e1e4",
        "surface-tint": "#c0c1ff",
        "on-tertiary": "#472a00",
        "inverse-on-surface": "#313032",
        "surface-container-low": "#1c1b1d",
        "surface-dim": "#131315",
        "outline-variant": "#464554",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary": "#003824",
        "inverse-primary": "#494bd6",
        "on-tertiary-container": "#3e2400",
        "secondary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#ffb95f",
        "on-surface-variant": "#c7c4d7",
        "on-secondary-container": "#00311f",
        "surface-container-high": "#2a2a2c",
        "tertiary": "#ffb95f",
        "surface-variant": "#353437",
        "surface-container-highest": "#353437",
        "primary-fixed": "#e1e0ff",
        "surface-container": "#201f21",
        "secondary": "#4edea3",
        "error-container": "#93000a",
        "on-error": "#690005",
        "background": "#131315",
        "tertiary-fixed": "#ffddb8",
        "on-primary-container": "#0d0096",
        "tertiary-container": "#ca8100",
        "primary": "#c0c1ff",
        "surface-container-lowest": "#0e0e10",
        "secondary-fixed-dim": "#4edea3",
        "inverse-surface": "#e5e1e4",
        "on-tertiary-fixed": "#2a1700",
        "surface": "#131315",
        "on-primary-fixed": "#07006c",
        "outline": "#908fa0",
        "surface-bright": "#39393b",
        "secondary-container": "#00a572"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "margin": "24px",
        "unit": "4px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "display-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md-mobile": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-md": ["30px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md-mobile": ["24px", { lineHeight: "30px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
